on:
  push:
  pull_request:
  schedule:
    - cron: "0 * * * *"

jobs:
  deploy:
    if: github.event_name	== 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/heads/results
          path: results
      - uses: actions/checkout@v2
        with:
          path: default
      - run: |
          cp -r results default/_data
      - run: npx vercel --confirm --token $VERCEL_TOKEN -S $VERCEL_SCOPE -n $VERCEL_NAME
        working-directory: default
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
          VERCEL_NAME: ${{ secrets.VERCEL_NAME }}

  deployToProduction:
    if: (github.event_name	== 'push' && github.ref == 'refs/heads/master') || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/heads/results
          path: results
      - uses: actions/checkout@v2
        with:
          path: default
      - run: |
          cp -r results default/_data
      - run: npx vercel --prod --confirm --token $VERCEL_TOKEN -S $VERCEL_SCOPE -n $VERCEL_NAME
        working-directory: default
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
          VERCEL_NAME: ${{ secrets.VERCEL_NAME }}