on:
  push:
  pull_request:
  schedule:
    - cron: "0 * * * *"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/heads/results
          path: results
      - uses: actions/checkout@v2
        with:
          path: default
      - run: |
          cp -r results default/_data/
          cd default
      - run: npm install
      - run: npm run test-pages
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: _data/results
      - uses: actions/upload-artifact@v2
        with:
          name: results-last-runs.json
          path: _data/results-last-runs.json
      - run: |
          rm -r ../results/results*
          cp -r ./_data/results* ../results
          cd ../results
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Commit results"
          git push
