on:
  push:
  pull_request:
  schedule:
    - cron: "0 * * * *"
    - cron: "30 * * * *"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get timestamp
        id: get-timestamp
        run: |
          echo "::set-output name=timestamp::$(/bin/date -u "+%s")"
        shell: bash
      - name: Cache results
        uses: actions/cache@v2
        with:
          path: _data/results
          key: ${{ runner.os }}-run-tests-results-${{ steps.get-timestamp.outputs.timestamp }}
          restore-keys: ${{ runner.os }}-run-tests-results-
      - name: Cache results-last-runs
        uses: actions/cache@v2
        with:
          path: _data/results-last-runs.json
          key: ${{ runner.os }}-run-tests-results-last-runs-${{ steps.get-timestamp.outputs.timestamp }}
          restore-keys: ${{ runner.os }}-run-tests-results-last-runs-
      - run: npm install
      - run: npm run test-pages
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: _data/results
      - uses: actions/upload-artifact@v2
        with:
          name: results-last-runs.json
          path: _data/results-last-runs.json
